version: '3.0'

services:
  explorer:
    build: .
    working_dir: /usr/src/app
    command: 'server'
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - redis_storage:/data


volumes:
  bundle:
  redis_storage: