version: '3.0'
x-app: &app
  image: kpi_explorer
  build: .
  working_dir: /usr/src/app
  volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
  depends_on:
    - redis
services:
  explorer:
    <<: *app
    command: 'server'
    ports:
      - 3000:3000

  worker:
    <<: *app
    command: bundle exec sidekiq -r ./lib/boot.rb

  redis:
    image: redis:alpine
    volumes:
      - redis_storage:/data


volumes:
  bundle:
  redis_storage:
